In [1]:
import pandas as pd
import numpy as np

In [53]:
df1 = pd.read_csv(r'C:\Users\marcos.sandovalr\Documents\Marcos Privada\Python Big Data\Python-TensorFlow-for-Machine-Learning-Neural-Network-Text-Classification-Tutorial\Velocidad-Promedio-Internet-2022.csv')
df2 = pd.read_excel(r"C:\Users\marcos.sandovalr\Documents\Marcos Privada\Python Big Data\Python-TensorFlow-for-Machine-Learning-Neural-Network-Text-Classification-Tutorial\Usuarios-Internet-2022.xlsx")
df3 = pd.read_excel(r"C:\Users\marcos.sandovalr\Documents\Marcos Privada\Python Big Data\Python-TensorFlow-for-Machine-Learning-Neural-Network-Text-Classification-Tutorial\Precios-Internet-2022.xlsx")
df1.head()

       Country  Avg \n(Mbit/s)Ookla
0       Canada                75.18
1  South Korea               117.95
2  Netherlands               108.33
3        Japan                44.05
4       Norway               134.73

In [74]:
df4 = pd.merge(df2,df3, left_on='Country or area' , right_on='Name')
df5 = pd.merge(df4,df1, left_on='Name', right_on='Country')
df6 = df5.drop(['Country code','Name','Country','Continental region'],axis=1)
internet_2022 = df6.rename(columns={'Country or area':'Pais','Internet users':'Usuarios de Internet','Population':'Poblacion','NO. OF Internet Plans':'Numero de Planes de Internet','Average price of 1GB (USD)':'Precio Promedio de 1GB (USD)','Cheapest 1GB for 30 days (USD)':'Precio Mas Barato por 1GB(USD)','Most expensive 1GB (USD)':'Precio Mas Caro por 1GB(USD)','Average price of 1GB (USD at the start of 2021)':'Precio Promedio de 1GB Inicio de 2021(USD)','Average price of 1GB (USD – at start of 2020)':'Precio Promedio de 1GB Inicio 2020(USD)','Avg \n(Mbit/s)Ookla':'Velocidad Internet'})
internet_202 = internet_2022.dropna()
internet_22 = internet_202[['Usuarios de Internet','Poblacion','Precio Promedio de 1GB (USD)','Precio Mas Barato por 1GB(USD)','Precio Mas Caro por 1GB(USD)','Velocidad Internet']].astype(int)
internet22 = internet_22.corr()
internet22.style.background_gradient()